# Netlify Build Configuration

[build]
  # This is the command to build your React frontend
  command = "npm run build"
  
  # The folder where your Flask app (Netlify Function) is located
  functions = "api/"
  
  # The folder that contains the built frontend to be published
  publish = "frontend/build"

[dev]
  # Local development settings (optional)
  framework = "create-react-app"
  targetPort = 3000

[[redirects]]
  # This rule proxies all API requests to your Flask function
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  # This rule handles client-side routing for your React app
  from = "/*"
  to = "/index.html"
  status = 200
